#Minecraft server properties
#Mon Feb 23 03:16:56 UTC 2026
allow-flight=true
difficulty=normal
enable-command-block=true
force-gamemode=true
gamemode=survival
hardcore=false
player-idle-timeout=0
pvp=true
view-distance=8
allow-nether=false
simulation-distance=32
spawn-monsters=false
spawn-protection=16
generate-structures=true
generator-settings={}
level-name=Megalopolis
level-seed=
level-type=minecraft\:normal
enforce-whitelist=false
white-list=false
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
function-permission-level=2
op-permission-level=4
accepts-transfers=true
enable-status=true
enforce-secure-profile=false
hide-online-players=false
max-players=20
motd=\u00a7l   \u00a7r         \u00a7a\u00a7lOfficial Megalopolis Server
online-mode=false
prevent-proxy-connections=false
server-ip=
server-port=25565
enable-query=false
query.port=25565
enable-rcon=false
rcon.password=
rcon.port=25575
require-resource-pack=true
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
bug-report-link=
debug=false
enable-jmx-monitoring=false
entity-broadcast-range-percentage=250
initial-disabled-packs=
initial-enabled-packs=vanilla
log-ips=true
max-chained-neighbor-updates=1000000
max-tick-time=60000
max-world-size=29999984
network-compression-threshold=256
pause-when-empty-seconds=-1
rate-limit=0
region-file-compression=lz4
sync-chunk-writes=true
text-filtering-config=
text-filtering-version=0
use-native-transport=true
enable-code-of-conduct=false
management-server-allowed-origins=
management-server-enabled=false
management-server-host=localhost
management-server-port=0
management-server-secret=Pw4mZIYJgu0BBEm17ksNQl5G8WT7E00mInBTVfcB
management-server-tls-enabled=true
management-server-tls-keystore=
management-server-tls-keystore-password=
status-heartbeat-interval=0

#Generated on https://mctools.org/server-properties-creator
