name = "Megalopolis"
author = "Flimsy Fox"
version = "3.8.0b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "295824a564695de5255e787bc618b733e7cb37eab7ce4a73012471824d28d4a5"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"

[options]
acceptable-game-versions = ["1.16.5", "1.20.1", "1.21.1"]
datapack-folder = "datapacks"
