name = "Megalopolis"
author = "Flimsy Fox"
version = "3.5.0b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab6eef1920f4a253a81ab6615917556d937ccb1a1eb117ea7df92eb717f1a976"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = ["1.16.5", "1.20.1", "1.21.1"]
datapack-folder = "datapacks"
