name = "Megalopolis"
author = "Flimsy Fox"
version = "3.1.0b"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2a2ddd3cea453b0c8765bcd3f6641f4cb31dcc5f8cc3fa135048f187a87c3aa"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"

[options]
acceptable-game-versions = ["1.20.1", "1.21.1"]
datapack-folder = "datapacks"
