#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Jun 08 03:54:10 CDT 2026
allowUnknownShaders=false
colorSpace=REC2020
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
