#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Mar 06 06:40:07 MST 2026
colorSpace=REC2020
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=16
shaderPack=ComplementaryUnbound_r5.6.1.zip
enableShaders=false
